[features]
seeds = false
skip-lint = false
[programs.devnet]
puzzle_box = "AeyNFWzsb2rhuQpgwoa6mfH6FzxT8FQ62GeBapdKanca"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/drkrueger/.config/solana/programs/puzzle-box.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
