[features]
seeds = false
skip-lint = false
[programs.devnet]
puzzle_box = "FzcS9Lmrwo5R71LjPuucgQqSc3T8xjWWPmbtDQNEpa4j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/drkrueger/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
